armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: update apt
        run: sudo apt update

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/ptitSeb/box64
          cd box64
          curl -d "Start cmake 😀" ntfy.sh/easonntfy
          mkdir build; cd build; cmake .. -D ARM_DYNAREC=ON -D CMAKE_BUILD_TYPE=RelWithDebInfo
          curl -d "Start make 😀" ntfy.sh/easonntfy
          make -j4
          curl -d "Finish make 😀" ntfy.sh/easonntfy
          sudo make install
          curl -d "Finish make install 😀" ntfy.sh/easonntfy
          sudo systemctl restart systemd-binfmt
